### ISSUE TITLE
Scrape publication lists

### ISSUE THREAD

**Issue by cssherry** [spectrum-app/spectrum_backend#20]
Scrape publications and their biases from https://mediabiasfactcheck.com

Similar to https://github.com/JeffreyATW/mbfc_crawler (part of http://jeffreyatw.com/blog/2016/11/check-news-bias-with-a-simple-browser-icon/ and https://chrome.google.com/webstore/detail/official-media-bias-fact/hdcpibgmmcnpjmmenengjgkkfohahegk?hl=en-US)

**Comment by jgerminario** [comment]
For after initial publication scaling

**Comment by jgerminario** [comment]
Added this to the roadmap Trello for June https://trello.com/c/s5QKJstv/28-build-out-more-publications. There's some trickiness here - we probably don't want to actively pull all these publications (backend won't be able to handle it) so we'll need some way to only pull associations when a user hits one of these 'secondary' sites
