### ISSUE TITLE
Suggested article when on moderate site

### ISSUE THREAD

**Issue by cssherry** [spectrum-app/spectrum_backend#25]
**An issue:**

1) When on moderate site, sometimes same article is given as "related" article (http://hosted2.ap.org/APDEFAULT/89ae8247abe8493fae24405546e9a1aa/Article_2017-02-27-US--Trump-Budget/id-f6daf76dd8e945b98c6fe103a050dbc2)
![screen shot 2017-03-25 at 8 17 18 am](https://cloud.githubusercontent.com/assets/6097953/24323495/a24b0a6c-1133-11e7-9d90-7f3930b9b58b.png)

**Couple questions:**

1) On Reuters and other moderate publishers, should we be suggesting other articles by the same publisher?
2) Should we be suggesting articles from other moderate publishers or from right/left publishers?

![screen shot 2017-03-25 at 6 41 16 am](https://cloud.githubusercontent.com/assets/6097953/24322684/8986c4b0-1126-11e7-8018-e95a1bbf5f9e.png)

**Comment by jgerminario** [comment]
This is fixed now
